In [2]:
import numpy as np
np.array([2])

array([2])

In [12]:
arr=np.array([[3,2],[4,5]])

In [13]:
arr.ndim


2

In [30]:
arr.itemsize

4

In [35]:
b.dtype

dtype('int32')

In [14]:
np.random.rand(5)

array([0.83177541, 0.33846316, 0.3562818 , 0.27729147, 0.42330818])

In [24]:
np.linspace(3,4,5,5)#1-start,5-end

array([3.  , 3.25, 3.5 , 3.75, 4.  ])

In [25]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [34]:
b=np.array([1,2,3,4,5])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x=np.arange(100)
y=np.arange(100)
col=np.arange(100)
plt.scatter(x,y,c=col)

NameError: name 'plt' is not defined